name: keqv
description: Convert the simplest file data format key=value between string and map.
version: 1.0.0
repository: https://github.com/rk0cc/keqv
environment: 
  sdk: ">=2.12.0 <3.0.0"
dev_dependencies:
  test: ^1.17.12
