name: keqv
description: Convert the simplest file data format key=value between string and map.
version: 2.0.0-pre.2
repository: https://github.com/rk0cc/keqv
funding:
  - https://github.com/sponsors/rk0cc
environment: 
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  meta: ^1.10.0
dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2

