name: Test
on:
  push:
    branches:
      - main
    paths:
      - lib/**.dart
      - test/**.dart
      - .github/workflows/dart.yml
jobs:
  test:
    name: Run Dart test
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
        dart-sdk:
          - stable
          - beta
          - dev
          - 2.12.4
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: ${{ matrix.dart-sdk }}
      - name: Install dependencies
        run: dart pub get
      - name: Do test
        run: dart test